export default {
	"SUPABASE_URL": "https://qlqsvedhqhjowlpbylvq.supabase.co",
	"SUPABASE_ANON_KEY":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFscXN2ZWRocWhqb3dscGJ5bHZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTMzNDc0MDEsImV4cCI6MjAwODkyMzQwMX0.ECi9MD7FJiKjPHs_bCZGrpWmdX9wp5LIDnIipzAxfQU"
}